"""change password column name

Revision ID: 0ab7d40001a5
Revises: 7872290b0785
Create Date: 2023-08-25 20:56:59.191062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab7d40001a5'
down_revision = '7872290b0785'
branch_labels = None
depends_on = None


def upgrade():
    op.alter_column('user', 'password', new_column_name='password_hash')


def downgrade():
    op.alter_column('users', 'password_hash', new_column_name='password')

# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('password_hash', sa.String(length=100), nullable=True))
#         batch_op.create_unique_constraint(None, ['name'])
#         batch_op.drop_column('password')

#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('user', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=True))
#         batch_op.drop_constraint(None, type_='unique')
#         batch_op.drop_column('password_hash')

#     # ### end Alembic commands ###
