"""empty message

Revision ID: 7872290b0785
Revises: b8b093bb3183
Create Date: 2023-08-20 16:00:08.144834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7872290b0785'
down_revision = 'b8b093bb3183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('confirmed', sa.Boolean(), nullable=True))
        # batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
